# This is a basic workflow to help you get started with Actions

name: CI
on:
  schedule:
    - cron: "0 0 * * *"
  push: {branches: ["master", "main"]}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  take-screenshot:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # SS website riau.go.id
      - name: screenshot-website
        uses: swinton/screenshot-website@v1.0.0
        with:
          source: https://www.riau.go.id/
          destination: riau-go-id.png 
        
      - name: Download SS Artifact
        uses: actions/download-artifact@v2


